import { app, BrowserWindow, nativeImage, shell } from 'electron';
import { join } from 'node:path';
import { existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { openDatabase, closeDatabase, getDatabase } from './db/connection.js';
import { seedDefaultCountriesIfEmpty } from './db/seed.js';
import { getAllSettings } from './db/repositories/settings.js';
import { initImagesDir } from './images.js';
import { registerIpcHandlers } from './ipc.js';
import { buildAppMenu } from './menu.js';
import { runAutoBackup } from './auto-backup.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

function resolveUserDataPaths(): { dataDir: string; dbPath: string; imagesDir: string } {
  const dataDir = join(app.getPath('userData'));
  if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });
  const dbPath = join(dataDir, 'hinged.db');
  const imagesDir = join(dataDir, 'Images');
  return { dataDir, dbPath, imagesDir };
}

/**
 * Path to the dev-time icon. Packaged builds get their icon from the app
 * bundle (generated by electron-builder from resources/icon.png at build
 * time) so this is only used when `npm run dev` is running.
 */
function devIconPath(): string {
  // In dev, __dirname is <repo>/electron/out/main, so back up to <repo>/electron/resources/icon.png
  return join(__dirname, '..', '..', 'resources', 'icon.png');
}

function createWindow(): void {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 900,
    minHeight: 600,
    show: false,
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    // Ignored on macOS (dock icon is set via app.dock.setIcon below), but
    // matters on Windows and Linux where it sets the taskbar/window icon.
    icon: !app.isPackaged && existsSync(devIconPath()) ? devIconPath() : undefined,
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: true,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  win.on('ready-to-show', () => {
    win.show();
    if (!app.isPackaged) win.webContents.openDevTools({ mode: 'detach' });
  });

  if (!app.isPackaged) {
    win.webContents.on('console-message', (_e, level, message, line, sourceId) => {
      // eslint-disable-next-line no-console
      console.log(`[renderer ${level}] ${message} (${sourceId}:${line})`);
    });
    win.webContents.on('render-process-gone', (_e, details) => {
      // eslint-disable-next-line no-console
      console.log('[render-process-gone]', details);
    });
    win.webContents.on('did-fail-load', (_e, code, desc, url) => {
      // eslint-disable-next-line no-console
      console.log(`[did-fail-load] ${code} ${desc} ${url}`);
    });
  }

  win.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: 'deny' };
  });

  // electron-vite dev server URL
  if (process.env.ELECTRON_RENDERER_URL) {
    void win.loadURL(process.env.ELECTRON_RENDERER_URL);
  } else {
    void win.loadFile(join(__dirname, '../renderer/index.html'));
  }
}

app.whenReady().then(() => {
  // Dev-time dock icon on macOS. Packaged builds use the icon from the
  // .app bundle and don't need this.
  if (!app.isPackaged && process.platform === 'darwin' && app.dock) {
    const iconPath = devIconPath();
    if (existsSync(iconPath)) {
      const img = nativeImage.createFromPath(iconPath);
      if (!img.isEmpty()) app.dock.setIcon(img);
    }
  }

  const { dbPath, imagesDir } = resolveUserDataPaths();
  openDatabase(dbPath);
  initImagesDir(imagesDir);
  const seeded = seedDefaultCountriesIfEmpty(getDatabase());
  if (seeded > 0) {
    // eslint-disable-next-line no-console
    console.log(`[hinged] seeded ${seeded} default countries`);
  }

  // Auto-backup: runs once on launch if the user has configured a target dir.
  const settings = getAllSettings(getDatabase());
  if (settings.autoBackupDir) {
    const keep = Number.parseInt(settings.autoBackupKeep, 10) || 5;
    const result = runAutoBackup(getDatabase(), settings.autoBackupDir, keep);
    if (result.ok) {
      // eslint-disable-next-line no-console
      console.log(`[hinged] auto-backup → ${result.path} (rotated ${result.rotatedCount ?? 0})`);
    } else {
      // eslint-disable-next-line no-console
      console.warn(`[hinged] auto-backup failed: ${result.error}`);
    }
  }

  registerIpcHandlers();
  buildAppMenu();

  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('before-quit', () => {
  closeDatabase();
});
